### ISSUE TITLE
CORE: Fix angular & EJS interaction

### ISSUE THREAD

**Issue by Unachieved** [gaskij/rpicampusmap#119]
Currently the inclusion of certain angular controllers interfere with the use of (ejs pass ins which which utilize aspects of angular e.g. ng-repeat for the browse in searchResults.ejs)

One can place all the js functionality in the pages corresponding angular controller and properly link the ejs file
Else
find propose another solution which can be applied across the board

**Comment by gaskij** [comment]
It'll probably be easiest to just do away with the ejs stuff and just use angular instead of trying to mix the two while they perform the same function.
