### ISSUE TITLE
FEATURE: Fix info displayed after clicking a location on map

### ISSUE THREAD

**Issue by tinaadams25** [gaskij/rpicampusmap#120]
Right now the name, description, and nickname of the location a user clicks on is not displayed properly after clicking the link to get to the page with information about the location.

**Comment by Xtreme765** [comment]
This issue does not exist in /main but does exist in /dev. It's likely due to the moving around of files into various folders. Currently investigating for an exact cause.

**Comment by Xtreme765** [comment]
This issue is purely due to the changes in dev, there is more location info to merge back into master from dev but overall this issue will be fixed simply by merging back into master or will reappear at a later date if any new implementation doesn't account for this.
