### ISSUE TITLE
CORE: Setup web hosting and app deployment

### ISSUE THREAD

**Issue by Chaotic-Cody** [gaskij/rpicampusmap#123]
Figure out which hosting service to use and deploy the app using the hosting service. 

This issue will be useful for testing user location tracking.

**Comment by gaskij** [comment]
I've used Heroku in the past, but Prof. Turner has also talked about getting it hosted by the school. I don't really know exactly what that entails, though.

**Comment by gaskij** [comment]
I'll be using Heroku for the time being to get it up and running. We can figure out school hosting later.
